#!/usr/bin/env node
/* RiverMath test suite: engine.js vs independent oracle (tests/expected.json,
   generated by tests/oracle.py) plus JS-only behavior checks. */
'use strict';
const R = require('../engine.js');
const exp = require('./expected.json');

let pass = 0, fail = 0;
const fails = [];
function ok(cond, name) {
  if (cond) { pass++; }
  else { fail++; fails.push(name); }
}
function close(a, b, tol, name) {
  ok(typeof a === 'number' && Math.abs(a - b) <= tol, `${name} (got ${a}, want ${b})`);
}

// ---- outs odds vs oracle ----
for (const [key, o] of Object.entries(exp.outs)) {
  const [outs, unseen] = key.split('/').map(Number);
  const r = R.outsOdds(outs, unseen);
  close(r.turn, o.turn, 1e-12, `outs ${key} turn`);
  close(r.riverAfterMiss, o.riverAfterMiss, 1e-12, `outs ${key} riverAfterMiss`);
  close(r.either, o.either, 1e-12, `outs ${key} either`);
  close(r.rule2, o.rule2, 1e-12, `outs ${key} rule2`);
  close(r.rule4, o.rule4, 1e-12, `outs ${key} rule4`);
  close(r.rule2Error, o.rule2 - o.riverAfterMiss, 1e-12, `outs ${key} rule2Error`);
  close(r.rule4Error, o.rule4 - o.either, 1e-12, `outs ${key} rule4Error`);
}

// ---- pot odds vs oracle ----
for (const [key, o] of Object.entries(exp.pot)) {
  const [p, b] = key.split('/').map(Number);
  const r = R.potOdds(p, b);
  close(r.required, o.required, 1e-12, `pot ${key} required`);
  ok(r.finalPot === o.finalPot, `pot ${key} finalPot`);
  close(r.ratio, o.ratio, 1e-12, `pot ${key} ratio`);
}

// ---- breakEvenOuts vs direct check ----
{
  const req = R.potOdds(100, 50).required; // 50/200 = 0.25
  const n = R.breakEvenOuts(req, 46);
  ok(n === 12, `breakEvenOuts river (got ${n}, want 12)`);
  ok(R.breakEvenOuts(0, 46) === 0, 'breakEvenOuts zero');
  ok(R.breakEvenOuts(9 / 46 - 1e-9, 46) === 9, 'breakEvenOuts just under 9/46');
}

// ---- evaluator categories vs oracle ----
const catHands = {
  royal: 'As Ks Qs Js Ts', wheel: 'Ad 2c 3h 4s 5d', quads: 'Ac Ad Ah As Kd',
  boat: 'Ac Ad Ah Ks Kd', flush7: 'As Qs 9s 6s 3s', straight9: '9d 8c 7h 6s 5d',
  trips: 'Qc Qd Qh 9s 2d', twopair: 'Jc Jd 8h 8s Ad', pair: 'Tc Td 9h 6s 3d',
  high: 'Ac Qd 9h 6s 3d'
};
for (const [name, hand] of Object.entries(catHands)) {
  ok(R.describeHand(R.parseCards(hand)) === exp.eval_categories[name],
    `category ${name} (got ${R.describeHand(R.parseCards(hand))})`);
}
// ordering chain
const order = ['high', 'pair', 'twopair', 'trips', 'wheel', 'straight9', 'flush7', 'boat', 'quads', 'royal'];
for (let i = 0; i < order.length - 1; i++) {
  ok(R.eval5(R.parseCards(catHands[order[i]])) < R.eval5(R.parseCards(catHands[order[i + 1]])),
    `ordering ${order[i]} < ${order[i + 1]}`);
}
// kicker sensitivity
ok(R.eval5(R.parseCards('Ac Kd 9h 6s 3d')) > R.eval5(R.parseCards('Ac Qd 9h 6s 3d')), 'kicker A>K... wait K>Q kicker');
ok(R.eval5(R.parseCards('Tc Td Ah 6s 3d')) > R.eval5(R.parseCards('Tc Td Kh 6s 3d')), 'pair kicker');
ok(R.eval5(R.parseCards('6h 5d 4c 3s 2d')) > R.eval5(R.parseCards('Ah 2d 3c 4s 5d')), '6-high straight beats wheel');

// ---- equity vs oracle ----
for (const [name, o] of Object.entries(exp.equity)) {
  const cfg = {
    flushdraw_vs_pair_flop: ['Ah Kh', '2c 2d', 'Qs Js 4d'],
    aa_vs_kk_flop: ['Ac Ad', 'Kc Kd', '2s 7h 9c'],
    ak_vs_pair_turn: ['Ah Kh', '2c 2d', 'Qs Js 4d 5c'],
    monster_vs_overpair_flop: ['As Ks', 'Qh Qd', 'Ts Js 2s'],
    showdown_board_straightflush_tie: ['As 2d', 'Kd Qh', '5c 6c 7c 8c 9c'],
    showdown_flush_vs_set: ['Ac Tc', '9h 9d', 'Kc 7c 2c 9s 3d']
  }[name];
  const r = R.equity(R.parseCards(cfg[0]), R.parseCards(cfg[1]), R.parseCards(cfg[2]));
  ok(!r.error, `equity ${name} no error`);
  close(r.win, o.win, 1e-9, `equity ${name} win`);
  close(r.tie, o.tie, 1e-9, `equity ${name} tie`);
  close(r.loss, o.loss, 1e-9, `equity ${name} loss`);
  ok(r.total === o.total, `equity ${name} total (got ${r.total}, want ${o.total})`);
  ok(r.exact === true, `equity ${name} exact flag`);
}

// ---- preflop Monte Carlo: determinism + published-band sanity ----
{
  const aa = R.parseCards('Ac Ad'), kk = R.parseCards('Kc Kd');
  const a = R.equity(aa, kk, [], 50000, 407);
  const b = R.equity(aa, kk, [], 50000, 407);
  ok(a.win === b.win && a.total === b.total, 'MC deterministic same seed');
  ok(a.exact === false && a.total === 50000, 'MC flags');
  ok(a.win > 0.79 && a.win < 0.84, `AA vs KK band (got ${a.win})`);
  const c = R.equity(aa, kk, [], 50000, 999);
  ok(Math.abs(c.win - a.win) < 0.01, 'MC seed stability');
  ok(Math.abs(a.win + a.tie + a.loss - 1) < 1e-9, 'MC sums to 1');
}

// ---- parse + validation ----
{
  ok(R.parseCards('AhKd').length === 2, 'parse compact');
  ok(R.parseCards('ah, kd').length === 2, 'parse lowercase comma');
  ok(R.parseCards('').length === 0, 'parse empty');
  ok(R.parseCards('Ah K').error !== undefined, 'parse odd token');
  ok(R.parseCards('Ah 1s').error !== undefined, 'parse bad rank');
  ok(R.parseCards('Ax Kd').error !== undefined, 'parse bad suit');
  ok(R.hasDuplicates(R.parseCards('Ah Ah')) === true, 'dup detect');
  const e = R.equity(R.parseCards('Ah Ad'), R.parseCards('Ah Kd'), []);
  ok(e.error === 'duplicate cards', 'equity dup error');
  ok(R.equity(R.parseCards('Ah'), R.parseCards('Kd Qs'), []).error !== undefined, 'equity arity error');
  ok(R.cardName(R.parseCards('Td')[0]) === 'Td', 'cardName roundtrip');
}

// ---- choose + DRAWS sanity ----
ok(R.choose(47, 2) === 1081, 'choose 47,2');
ok(R.choose(45, 2) === 990, 'choose 45,2');
ok(R.choose(46, 1) === 46, 'choose 46,1');
ok(R.choose(5, 0) === 1, 'choose n,0');
ok(R.DRAWS.length === 6 && R.DRAWS.every(d => d.outs >= 4 && d.outs <= 15), 'DRAWS table sane');
const flushDraw = R.DRAWS.find(d => d.id === 'flush');
ok(flushDraw && flushDraw.outs === 9, 'flush draw is 9 outs');
// classic published spot: 9 outs from flop ~34.97%
close(R.outsOdds(9, 47).either, 0.34968, 1e-4, 'published 9-out both-streets value');

console.log(`\n${pass} passed, ${fail} failed`);
if (fail) { console.log('FAILURES:'); fails.forEach(f => console.log(' - ' + f)); process.exit(1); }
